language: node_js
node_js:
- '8'
before_script:
- npm run build-client
deploy:
  provider: cloudfoundry
  api: https://api.eu-gb.bluemix.net
  username: $BLUEMIX_USERNAME
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    repo: hunttis/alkomaholi
    branch: master
